#pragma checksum "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D0B703B9759376B17358EEB65F0748FB39D1002A6DF9D520F71EC8BB93E38199"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// CreateDeptAccountWindow
    /// </summary>
    public partial class CreateDeptAccountWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 79 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtInfo;
        
        #line default
        #line hidden
        
        
        #line 84 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtUsername;
        
        #line default
        #line hidden
        
        
        #line 88 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdPassword;
        
        #line default
        #line hidden
        
        
        #line 89 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtPwdVisible;
        
        #line default
        #line hidden
        
        
        #line 93 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdConfirm;
        
        #line default
        #line hidden
        
        
        #line 94 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtConfVisible;
        
        #line default
        #line hidden
        
        
        #line 97 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkShow;
        
        #line default
        #line hidden
        
        
        #line 104 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 119 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCreate;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/createdeptacc" +
                    "ountwindow.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtUsername = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.PwdPassword = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 4:
            this.TxtPwdVisible = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.PwdConfirm = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 6:
            this.TxtConfVisible = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.ChkShow = ((System.Windows.Controls.CheckBox)(target));
            
            #line 98 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
            this.ChkShow.Checked += new System.Windows.RoutedEventHandler(this.ChkShow_Changed);
            
            #line default
            #line hidden
            
            #line 98 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
            this.ChkShow.Unchecked += new System.Windows.RoutedEventHandler(this.ChkShow_Changed);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 108 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.BtnCreate = ((System.Windows.Controls.Button)(target));
            
            #line 122 "Wpf\Admin\AccountManagement\Dialogs\CreateDeptAccountWindow.xaml"
            this.BtnCreate.Click += new System.Windows.RoutedEventHandler(this.BtnCreate_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

