#pragma checksum "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2420B4623DF161CD6D803DE65427DDA6E4F02F0AE1DC75EC706A9044474C8DA5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Dialogs {
    
    
    /// <summary>
    /// EditBatchWindow
    /// </summary>
    public partial class EditBatchWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 77 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSubtitle;
        
        #line default
        #line hidden
        
        
        #line 80 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StatusBadge;
        
        #line default
        #line hidden
        
        
        #line 83 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtStatusBadge;
        
        #line default
        #line hidden
        
        
        #line 101 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtBatchId;
        
        #line default
        #line hidden
        
        
        #line 105 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtOriginalQty;
        
        #line default
        #line hidden
        
        
        #line 108 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PnlRemarks;
        
        #line default
        #line hidden
        
        
        #line 110 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtRemarks;
        
        #line default
        #line hidden
        
        
        #line 121 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ModelCountBadge;
        
        #line default
        #line hidden
        
        
        #line 124 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtModelCount;
        
        #line default
        #line hidden
        
        
        #line 129 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtModelsLoading;
        
        #line default
        #line hidden
        
        
        #line 133 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ModelsBorder;
        
        #line default
        #line hidden
        
        
        #line 136 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ModelLinesList;
        
        #line default
        #line hidden
        
        
        #line 186 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbVendor;
        
        #line default
        #line hidden
        
        
        #line 190 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtVendorHint;
        
        #line default
        #line hidden
        
        
        #line 196 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PnlTransfer;
        
        #line default
        #line hidden
        
        
        #line 216 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/dialogs/editbatchwindow.x" +
                    "aml", System.UriKind.Relative);
            
            #line 1 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtSubtitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.StatusBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.TxtStatusBadge = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtBatchId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.TxtOriginalQty = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.PnlRemarks = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 7:
            this.TxtRemarks = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.ModelCountBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.TxtModelCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.TxtModelsLoading = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.ModelsBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.ModelLinesList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 13:
            this.CmbVendor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.TxtVendorHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.PnlTransfer = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 16:
            
            #line 201 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnTransferCartridges_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 214 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.BtnSave = ((System.Windows.Controls.Button)(target));
            
            #line 217 "WPF\CartridgeManagement\Dialogs\EditBatchWindow.xaml"
            this.BtnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

