#pragma checksum "Wpf\Search\Views\SearchView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "407CB7E120439F90AC00AD9F124955D5E75E2466D16100E0552C08A4763A8CA9"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.Wpf.Search.Converters;


namespace Yakult.Inventory.App.Wpf.Search.Views {
    
    
    /// <summary>
    /// SearchView
    /// </summary>
    public partial class SearchView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 286 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SearchBorder;
        
        #line default
        #line hidden
        
        
        #line 310 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock WatermarkHint;
        
        #line default
        #line hidden
        
        
        #line 325 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchBox;
        
        #line default
        #line hidden
        
        
        #line 346 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup SuggestionsPopup;
        
        #line default
        #line hidden
        
        
        #line 361 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox SuggestionsList;
        
        #line default
        #line hidden
        
        
        #line 380 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FilterButton;
        
        #line default
        #line hidden
        
        
        #line 481 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image LogoImage;
        
        #line default
        #line hidden
        
        
        #line 486 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CenterSearchBorder;
        
        #line default
        #line hidden
        
        
        #line 521 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CenterSearchBox;
        
        #line default
        #line hidden
        
        
        #line 549 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox CenterSuggestionsList;
        
        #line default
        #line hidden
        
        
        #line 847 "Wpf\Search\Views\SearchView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox JumpToPageBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/search/views/searchview.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\Search\Views\SearchView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SearchBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.WatermarkHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.SearchBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 332 "Wpf\Search\Views\SearchView.xaml"
            this.SearchBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.SearchBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 4:
            this.SuggestionsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 5:
            this.SuggestionsList = ((System.Windows.Controls.ListBox)(target));
            
            #line 366 "Wpf\Search\Views\SearchView.xaml"
            this.SuggestionsList.PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.SuggestionsList_Click);
            
            #line default
            #line hidden
            
            #line 367 "Wpf\Search\Views\SearchView.xaml"
            this.SuggestionsList.KeyDown += new System.Windows.Input.KeyEventHandler(this.SuggestionsList_KeyDown);
            
            #line default
            #line hidden
            return;
            case 6:
            this.FilterButton = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.LogoImage = ((System.Windows.Controls.Image)(target));
            return;
            case 8:
            this.CenterSearchBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.CenterSearchBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 529 "Wpf\Search\Views\SearchView.xaml"
            this.CenterSearchBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.CenterSearchBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 10:
            this.CenterSuggestionsList = ((System.Windows.Controls.ListBox)(target));
            
            #line 554 "Wpf\Search\Views\SearchView.xaml"
            this.CenterSuggestionsList.PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.CenterSuggestionsList_Click);
            
            #line default
            #line hidden
            
            #line 555 "Wpf\Search\Views\SearchView.xaml"
            this.CenterSuggestionsList.KeyDown += new System.Windows.Input.KeyEventHandler(this.CenterSuggestionsList_KeyDown);
            
            #line default
            #line hidden
            return;
            case 11:
            this.JumpToPageBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 852 "Wpf\Search\Views\SearchView.xaml"
            this.JumpToPageBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.JumpToPageBox_KeyDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

