#pragma checksum "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "05F89136C2E5AC7425441D0EBAEA1834F9DED5BE3C28F3958A0C5AEB273AEAEC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Dialogs {
    
    
    /// <summary>
    /// AssignReturnsDialog
    /// </summary>
    public partial class AssignReturnsDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 120 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse Dot1;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Lbl1;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle Connector;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse Dot2;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Lbl2;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Step1Panel;
        
        #line default
        #line hidden
        
        
        #line 173 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbModelFilter;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkSelectAll;
        
        #line default
        #line hidden
        
        
        #line 184 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ReturnsGrid;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSelectionStatus;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid Step2Panel;
        
        #line default
        #line hidden
        
        
        #line 227 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtStep2Summary;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RadNew;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RadExisting;
        
        #line default
        #line hidden
        
        
        #line 248 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PnlNew;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbVendor;
        
        #line default
        #line hidden
        
        
        #line 269 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtRemarks;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PnlExisting;
        
        #line default
        #line hidden
        
        
        #line 279 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbExistingBatch;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ModelCards;
        
        #line default
        #line hidden
        
        
        #line 353 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 357 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnBack;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNext;
        
        #line default
        #line hidden
        
        
        #line 363 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnConfirm;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/dialogs/assignreturnsdial" +
                    "og.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Dot1 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 2:
            this.Lbl1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.Connector = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 4:
            this.Dot2 = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 5:
            this.Lbl2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.Step1Panel = ((System.Windows.Controls.Grid)(target));
            return;
            case 7:
            this.CmbModelFilter = ((System.Windows.Controls.ComboBox)(target));
            
            #line 175 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.CmbModelFilter.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbModelFilter_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ChkSelectAll = ((System.Windows.Controls.CheckBox)(target));
            
            #line 178 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.ChkSelectAll.Checked += new System.Windows.RoutedEventHandler(this.ChkSelectAll_CheckChanged);
            
            #line default
            #line hidden
            
            #line 179 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.ChkSelectAll.Unchecked += new System.Windows.RoutedEventHandler(this.ChkSelectAll_CheckChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ReturnsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 11:
            this.TxtSelectionStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.Step2Panel = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.TxtStep2Summary = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.RadNew = ((System.Windows.Controls.RadioButton)(target));
            
            #line 239 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.RadNew.Checked += new System.Windows.RoutedEventHandler(this.RadBatchMode_Changed);
            
            #line default
            #line hidden
            return;
            case 15:
            this.RadExisting = ((System.Windows.Controls.RadioButton)(target));
            
            #line 244 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.RadExisting.Checked += new System.Windows.RoutedEventHandler(this.RadBatchMode_Changed);
            
            #line default
            #line hidden
            return;
            case 16:
            this.PnlNew = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 17:
            this.CmbVendor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.TxtRemarks = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.PnlExisting = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 20:
            this.CmbExistingBatch = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 21:
            this.ModelCards = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 23:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 355 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.BtnBack = ((System.Windows.Controls.Button)(target));
            
            #line 359 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.BtnBack.Click += new System.Windows.RoutedEventHandler(this.BtnBack_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.BtnNext = ((System.Windows.Controls.Button)(target));
            
            #line 362 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.BtnNext.Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.BtnConfirm = ((System.Windows.Controls.Button)(target));
            
            #line 365 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            this.BtnConfirm.Click += new System.Windows.RoutedEventHandler(this.BtnConfirm_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 10:
            
            #line 191 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.RowCheckBox_Click);
            
            #line default
            #line hidden
            break;
            case 22:
            
            #line 322 "..\..\..\..\..\WPF\CartridgeManagement\Dialogs\AssignReturnsDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnRemoveModel_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

