#pragma checksum "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D9D0DE4461B2CA3FF71B6317CDEBC85841C7AB556ADE760F36C370A677044F36"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// ChangeDeptPasswordWindow
    /// </summary>
    public partial class ChangeDeptPasswordWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 89 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCompanyLabel;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCompanyValue;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtDeptLabel;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtDeptValue;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtBranchLabel;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtBranchValue;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdNew;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtNewVisible;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdConfirm;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtConfVisible;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkShow;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnOk;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/changedeptpas" +
                    "swordwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtCompanyLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtCompanyValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtDeptLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtDeptValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.TxtBranchLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.TxtBranchValue = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.PwdNew = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 8:
            this.TxtNewVisible = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.PwdConfirm = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 10:
            this.TxtConfVisible = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.ChkShow = ((System.Windows.Controls.CheckBox)(target));
            
            #line 109 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
            this.ChkShow.Checked += new System.Windows.RoutedEventHandler(this.ChkShow_Changed);
            
            #line default
            #line hidden
            
            #line 109 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
            this.ChkShow.Unchecked += new System.Windows.RoutedEventHandler(this.ChkShow_Changed);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 119 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BtnOk = ((System.Windows.Controls.Button)(target));
            
            #line 132 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ChangeDeptPasswordWindow.xaml"
            this.BtnOk.Click += new System.Windows.RoutedEventHandler(this.BtnOk_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

