#pragma checksum "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0BAB77A3263F5627926B0CCBD157F37F771F2E280BD7D476F70CE1683F76AB8D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// ColumnFilterWindow
    /// </summary>
    public partial class ColumnFilterWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 51 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtHeader;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox FilterList;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCount;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/columnfilterw" +
                    "indow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 62 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            this.TxtSearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtSearch_TextChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 85 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSelectAll_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 87 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClearAll_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.FilterList = ((System.Windows.Controls.ListBox)(target));
            return;
            case 7:
            this.TxtCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            
            #line 152 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnApply_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 157 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClearFilter_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 161 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 6:
            
            #line 125 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.AnyCheckBox_Changed);
            
            #line default
            #line hidden
            
            #line 126 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ColumnFilterWindow.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.AnyCheckBox_Changed);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

