#pragma checksum "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0D052F6D420B4660FCEF8D8A8B009277355748B1658249B40378257CEB9630C6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// EditDeptAccountWindow
    /// </summary>
    public partial class EditDeptAccountWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 66 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCompany;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtDept;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtBranch;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtUsername;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkIsActive;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CboEmail;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/editdeptaccou" +
                    "ntwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtCompany = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtDept = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtBranch = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtUsername = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.ChkIsActive = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.CboEmail = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 96 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnSave = ((System.Windows.Controls.Button)(target));
            
            #line 109 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\EditDeptAccountWindow.xaml"
            this.BtnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

