#pragma checksum "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "853DFA4602E67F00DDA2630E82F7DE220E2864D9F030C66F574F6D5D42B4CA9F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// ShowDeptPasswordWindow
    /// </summary>
    public partial class ShowDeptPasswordWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 36 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCompany;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtDept;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtBranch;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtUsername;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCopy;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPassword;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/showdeptpassw" +
                    "ordwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtCompany = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtDept = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtBranch = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtUsername = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.BtnCopy = ((System.Windows.Controls.Button)(target));
            
            #line 54 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
            this.BtnCopy.Click += new System.Windows.RoutedEventHandler(this.BtnCopy_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TxtPassword = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            
            #line 84 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Dialogs\ShowDeptPasswordWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

