#pragma checksum "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2DCEE6490C8B888D8DD5DD2412A464FABA78454D0A6BDEE0E124AD87AF702038"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.RequestPortal.AuthorizeRequest.ViewModels;


namespace Yakult.Inventory.App.WPF.RequestPortal.AuthorizeRequest.Views {
    
    
    /// <summary>
    /// AuthorizeRequestView
    /// </summary>
    public partial class AuthorizeRequestView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 30 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourHeaderBar;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourQueuePanel;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourSearchArea;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox tourQueueList;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer tourDetailScroll;
        
        #line default
        #line hidden
        
        
        #line 288 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourRequestDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 367 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourCartridgeCard;
        
        #line default
        #line hidden
        
        
        #line 449 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourPreviewCard;
        
        #line default
        #line hidden
        
        
        #line 631 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourSignatureCard;
        
        #line default
        #line hidden
        
        
        #line 647 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tourDrawTabBtn;
        
        #line default
        #line hidden
        
        
        #line 685 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tourUploadTabBtn;
        
        #line default
        #line hidden
        
        
        #line 758 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.InkCanvas inkCanvas;
        
        #line default
        #line hidden
        
        
        #line 770 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock drawHint;
        
        #line default
        #line hidden
        
        
        #line 824 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel tourClearBtnRow;
        
        #line default
        #line hidden
        
        
        #line 933 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourActionCard;
        
        #line default
        #line hidden
        
        
        #line 970 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tourNotesBox;
        
        #line default
        #line hidden
        
        
        #line 990 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tourApproveBtn;
        
        #line default
        #line hidden
        
        
        #line 1030 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button tourRejectBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/requestportal/authorizerequest/views/authoriz" +
                    "erequestview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\RequestPortal\AuthorizeRequest\Views\AuthorizeRequestView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tourHeaderBar = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.tourQueuePanel = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.tourSearchArea = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.tourQueueList = ((System.Windows.Controls.ListBox)(target));
            return;
            case 5:
            this.tourDetailScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 6:
            this.tourRequestDetailsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.tourCartridgeCard = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.tourPreviewCard = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.tourSignatureCard = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.tourDrawTabBtn = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.tourUploadTabBtn = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.inkCanvas = ((System.Windows.Controls.InkCanvas)(target));
            return;
            case 13:
            this.drawHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.tourClearBtnRow = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 15:
            this.tourActionCard = ((System.Windows.Controls.Border)(target));
            return;
            case 16:
            this.tourNotesBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.tourApproveBtn = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.tourRejectBtn = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

