#pragma checksum "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A017905821A4BEDC00E118570D200A9C95749DC64BA41CBD25CD451CAA442157"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Software {
    
    
    /// <summary>
    /// SoftwareServiceSetDialog
    /// </summary>
    public partial class SoftwareServiceSetDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 281 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BtnMaximizeGlyph;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtDocumentNumber;
        
        #line default
        #line hidden
        
        
        #line 343 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DtpDocumentDate;
        
        #line default
        #line hidden
        
        
        #line 354 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DtpStartDate;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkHasContractPeriod;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtReferenceNumber;
        
        #line default
        #line hidden
        
        
        #line 396 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCompany;
        
        #line default
        #line hidden
        
        
        #line 407 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbDistributor;
        
        #line default
        #line hidden
        
        
        #line 418 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DtpEndDate;
        
        #line default
        #line hidden
        
        
        #line 429 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbStatus;
        
        #line default
        #line hidden
        
        
        #line 453 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ItemsGrid;
        
        #line default
        #line hidden
        
        
        #line 631 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddItem;
        
        #line default
        #line hidden
        
        
        #line 636 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRemoveItem;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/software/softwareservicesetdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 271 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 280 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMinimizeClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.BtnMaximizeGlyph = ((System.Windows.Controls.TextBlock)(target));
            
            #line 285 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.BtnMaximizeGlyph.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMaximizeClick);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 289 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TxtDocumentNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.DtpDocumentDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 7:
            this.DtpStartDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 8:
            this.ChkHasContractPeriod = ((System.Windows.Controls.CheckBox)(target));
            
            #line 369 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.ChkHasContractPeriod.Checked += new System.Windows.RoutedEventHandler(this.ChkContractPeriod_Changed);
            
            #line default
            #line hidden
            
            #line 370 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.ChkHasContractPeriod.Unchecked += new System.Windows.RoutedEventHandler(this.ChkContractPeriod_Changed);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TxtReferenceNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.CmbCompany = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.CmbDistributor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.DtpEndDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 13:
            this.CmbStatus = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.ItemsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 469 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.ItemsGrid.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ItemsGrid_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 15:
            this.BtnAddItem = ((System.Windows.Controls.Button)(target));
            
            #line 635 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.BtnAddItem.Click += new System.Windows.RoutedEventHandler(this.BtnAddItem_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.BtnRemoveItem = ((System.Windows.Controls.Button)(target));
            
            #line 640 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            this.BtnRemoveItem.Click += new System.Windows.RoutedEventHandler(this.BtnRemoveItem_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 648 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 652 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnPrint_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 655 "..\..\..\..\Pages\Software\SoftwareServiceSetDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

