#pragma checksum "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "72287B25DE87A0761297260A571051C35ED47C3985ADF2EA6D93873A50ED320F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;
using Yakult.Inventory.App.WPF.RequestPortal.NewRequest.ViewModels;


namespace Yakult.Inventory.App.WPF.RequestPortal.NewRequest.Views {
    
    
    /// <summary>
    /// NewRequestView
    /// </summary>
    public partial class NewRequestView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 525 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RequestDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 530 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RequesterIdentityPanel;
        
        #line default
        #line hidden
        
        
        #line 569 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel DeptEmployeeSelectorPanel;
        
        #line default
        #line hidden
        
        
        #line 597 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CartridgeSelectionCard;
        
        #line default
        #line hidden
        
        
        #line 599 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CartridgeSelectionHeader;
        
        #line default
        #line hidden
        
        
        #line 608 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CartridgeModelCombo;
        
        #line default
        #line hidden
        
        
        #line 643 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border QtySpinnerBorder;
        
        #line default
        #line hidden
        
        
        #line 679 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReturnedEmptyLabel;
        
        #line default
        #line hidden
        
        
        #line 685 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ReturnedEmptyRow;
        
        #line default
        #line hidden
        
        
        #line 767 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddToRequestButton;
        
        #line default
        #line hidden
        
        
        #line 776 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RequestItemsCard;
        
        #line default
        #line hidden
        
        
        #line 784 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RequestItemsHeader;
        
        #line default
        #line hidden
        
        
        #line 900 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FulfillmentCard;
        
        #line default
        #line hidden
        
        
        #line 902 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FulfillmentHeader;
        
        #line default
        #line hidden
        
        
        #line 1095 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ActionBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/requestportal/newrequest/views/newrequestview" +
                    ".xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\RequestPortal\NewRequest\Views\NewRequestView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RequestDetailsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.RequesterIdentityPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.DeptEmployeeSelectorPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.CartridgeSelectionCard = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.CartridgeSelectionHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.CartridgeModelCombo = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.QtySpinnerBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.ReturnedEmptyLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.ReturnedEmptyRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.AddToRequestButton = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.RequestItemsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.RequestItemsHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.FulfillmentCard = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.FulfillmentHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.ActionBar = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

