#pragma checksum "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "2AC95C5FE1D2661E8F0A27B3CF07AAA9DEE42003BBED45EFD22039F8DE59BCEB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Views {
    
    
    /// <summary>
    /// EmployeeManagementView
    /// </summary>
    public partial class EmployeeManagementView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 358 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefresh;
        
        #line default
        #line hidden
        
        
        #line 383 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAdd;
        
        #line default
        #line hidden
        
        
        #line 384 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnEdit;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnArchive;
        
        #line default
        #line hidden
        
        
        #line 386 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnExport;
        
        #line default
        #line hidden
        
        
        #line 387 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnImport;
        
        #line default
        #line hidden
        
        
        #line 388 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnTemplate;
        
        #line default
        #line hidden
        
        
        #line 406 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 413 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CboFilter;
        
        #line default
        #line hidden
        
        
        #line 422 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkShowArchived;
        
        #line default
        #line hidden
        
        
        #line 429 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StatusBorder;
        
        #line default
        #line hidden
        
        
        #line 439 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid MainGrid;
        
        #line default
        #line hidden
        
        
        #line 584 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColDeptEmail;
        
        #line default
        #line hidden
        
        
        #line 606 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColBranchEmail;
        
        #line default
        #line hidden
        
        
        #line 628 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColPersonalEmail;
        
        #line default
        #line hidden
        
        
        #line 656 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnFirst;
        
        #line default
        #line hidden
        
        
        #line 661 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrev;
        
        #line default
        #line hidden
        
        
        #line 669 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNext;
        
        #line default
        #line hidden
        
        
        #line 674 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLast;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/views/employeemanagem" +
                    "entview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 361 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnRefresh.Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 383 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnAdd.Click += new System.Windows.RoutedEventHandler(this.BtnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.BtnEdit = ((System.Windows.Controls.Button)(target));
            
            #line 384 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnEdit.Click += new System.Windows.RoutedEventHandler(this.BtnEdit_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.BtnArchive = ((System.Windows.Controls.Button)(target));
            
            #line 385 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnArchive.Click += new System.Windows.RoutedEventHandler(this.BtnArchive_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BtnExport = ((System.Windows.Controls.Button)(target));
            
            #line 386 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnExport.Click += new System.Windows.RoutedEventHandler(this.BtnExport_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BtnImport = ((System.Windows.Controls.Button)(target));
            
            #line 387 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnImport.Click += new System.Windows.RoutedEventHandler(this.BtnImport_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.BtnTemplate = ((System.Windows.Controls.Button)(target));
            
            #line 388 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnTemplate.Click += new System.Windows.RoutedEventHandler(this.BtnTemplate_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 392 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.SelectedBadge_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.CboFilter = ((System.Windows.Controls.ComboBox)(target));
            
            #line 417 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.CboFilter.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CboFilter_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ChkShowArchived = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.StatusBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.MainGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 457 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.MainGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.MainGrid_MouseDoubleClick);
            
            #line default
            #line hidden
            
            #line 458 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.MainGrid.CellEditEnding += new System.EventHandler<System.Windows.Controls.DataGridCellEditEndingEventArgs>(this.MainGrid_CellEditEnding);
            
            #line default
            #line hidden
            
            #line 459 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.MainGrid.BeginningEdit += new System.EventHandler<System.Windows.Controls.DataGridBeginningEditEventArgs>(this.MainGrid_BeginningEdit);
            
            #line default
            #line hidden
            
            #line 460 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.MainGrid.Sorting += new System.Windows.Controls.DataGridSortingEventHandler(this.MainGrid_Sorting);
            
            #line default
            #line hidden
            
            #line 461 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.MainGrid.AddHandler(System.Windows.Controls.Primitives.ButtonBase.ClickEvent, new System.Windows.RoutedEventHandler(this.MainGrid_HeaderButtonClick));
            
            #line default
            #line hidden
            return;
            case 15:
            this.ColDeptEmail = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 16:
            this.ColBranchEmail = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 17:
            this.ColPersonalEmail = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 18:
            this.BtnFirst = ((System.Windows.Controls.Button)(target));
            
            #line 660 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnFirst.Click += new System.Windows.RoutedEventHandler(this.BtnFirst_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.BtnPrev = ((System.Windows.Controls.Button)(target));
            
            #line 665 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnPrev.Click += new System.Windows.RoutedEventHandler(this.BtnPrev_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.BtnNext = ((System.Windows.Controls.Button)(target));
            
            #line 673 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnNext.Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.BtnLast = ((System.Windows.Controls.Button)(target));
            
            #line 678 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            this.BtnLast.Click += new System.Windows.RoutedEventHandler(this.BtnLast_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 14:
            
            #line 483 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Loaded += new System.Windows.RoutedEventHandler(this.ChkSelectAllHeader_Loaded);
            
            #line default
            #line hidden
            
            #line 484 "..\..\..\..\..\..\Wpf\Admin\AccountManagement\Views\EmployeeManagementView.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.ChkSelectAll_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

