#pragma checksum "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "64EF0D5BA55B675A7D93260F7363B1891BCA770E9C549E99E5F31F94E98BAD63"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Request {
    
    
    /// <summary>
    /// BatchAddRequestDialog
    /// </summary>
    public partial class BatchAddRequestDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 333 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BtnMaximizeGlyph;
        
        #line default
        #line hidden
        
        
        #line 358 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtInfoBanner;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblOrgRowPrefix;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCompany;
        
        #line default
        #line hidden
        
        
        #line 378 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbDepartment;
        
        #line default
        #line hidden
        
        
        #line 386 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbBranch;
        
        #line default
        #line hidden
        
        
        #line 392 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkNoEmployee;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel PnlEmployee;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblEmployee;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid GridEmployee;
        
        #line default
        #line hidden
        
        
        #line 402 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtEmployee;
        
        #line default
        #line hidden
        
        
        #line 410 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnClearEmployee;
        
        #line default
        #line hidden
        
        
        #line 420 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup PopupEmployee;
        
        #line default
        #line hidden
        
        
        #line 430 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LstEmployeeSearch;
        
        #line default
        #line hidden
        
        
        #line 437 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddEmployee;
        
        #line default
        #line hidden
        
        
        #line 442 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DgvRequests;
        
        #line default
        #line hidden
        
        
        #line 486 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn ColCategory;
        
        #line default
        #line hidden
        
        
        #line 510 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn ColItem;
        
        #line default
        #line hidden
        
        
        #line 608 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtDescription;
        
        #line default
        #line hidden
        
        
        #line 616 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtRemarks;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddRow;
        
        #line default
        #line hidden
        
        
        #line 635 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRemoveRow;
        
        #line default
        #line hidden
        
        
        #line 639 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 641 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/request/batchaddrequestdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 19 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((Yakult.Inventory.App.Pages.Request.BatchAddRequestDialog)(target)).PreviewMouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Window_PreviewMouseDown);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 326 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 332 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMinimizeClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BtnMaximizeGlyph = ((System.Windows.Controls.TextBlock)(target));
            
            #line 335 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnMaximizeGlyph.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMaximizeClick);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 338 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TxtInfoBanner = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.LblOrgRowPrefix = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.CmbCompany = ((System.Windows.Controls.ComboBox)(target));
            
            #line 372 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbCompany.GotFocus += new System.Windows.RoutedEventHandler(this.CmbOrg_GotFocus);
            
            #line default
            #line hidden
            
            #line 373 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbCompany.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CmbOrg_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 374 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbCompany.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbOrg_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 375 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbCompany.DropDownClosed += new System.EventHandler(this.CmbOrg_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 10:
            this.CmbDepartment = ((System.Windows.Controls.ComboBox)(target));
            
            #line 380 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbDepartment.GotFocus += new System.Windows.RoutedEventHandler(this.CmbOrg_GotFocus);
            
            #line default
            #line hidden
            
            #line 381 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbDepartment.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CmbOrg_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 382 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbDepartment.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbOrg_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 383 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbDepartment.DropDownClosed += new System.EventHandler(this.CmbOrg_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 11:
            this.CmbBranch = ((System.Windows.Controls.ComboBox)(target));
            
            #line 388 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbBranch.GotFocus += new System.Windows.RoutedEventHandler(this.CmbOrg_GotFocus);
            
            #line default
            #line hidden
            
            #line 389 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbBranch.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CmbOrg_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 390 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbBranch.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbOrg_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 391 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.CmbBranch.DropDownClosed += new System.EventHandler(this.CmbOrg_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 12:
            this.ChkNoEmployee = ((System.Windows.Controls.CheckBox)(target));
            
            #line 394 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.ChkNoEmployee.Checked += new System.Windows.RoutedEventHandler(this.ChkNoEmployee_Changed);
            
            #line default
            #line hidden
            
            #line 394 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.ChkNoEmployee.Unchecked += new System.Windows.RoutedEventHandler(this.ChkNoEmployee_Changed);
            
            #line default
            #line hidden
            return;
            case 13:
            this.PnlEmployee = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 14:
            this.LblEmployee = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.GridEmployee = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.TxtEmployee = ((System.Windows.Controls.TextBox)(target));
            
            #line 406 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.TxtEmployee.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtEmployee_TextChanged);
            
            #line default
            #line hidden
            
            #line 407 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.TxtEmployee.GotFocus += new System.Windows.RoutedEventHandler(this.TxtEmployee_GotFocus);
            
            #line default
            #line hidden
            
            #line 408 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.TxtEmployee.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TxtEmployee_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 409 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.TxtEmployee.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.TxtEmployee_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 17:
            this.BtnClearEmployee = ((System.Windows.Controls.Button)(target));
            
            #line 419 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnClearEmployee.Click += new System.Windows.RoutedEventHandler(this.BtnClearEmployee_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.PopupEmployee = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 19:
            this.LstEmployeeSearch = ((System.Windows.Controls.ListBox)(target));
            
            #line 433 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.LstEmployeeSearch.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.LstEmployeeSearch_MouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 20:
            this.BtnAddEmployee = ((System.Windows.Controls.Button)(target));
            
            #line 438 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnAddEmployee.Click += new System.Windows.RoutedEventHandler(this.BtnAddEmployee_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.DgvRequests = ((System.Windows.Controls.DataGrid)(target));
            
            #line 460 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.DgvRequests.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DgvRequests_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 461 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.DgvRequests.CellEditEnding += new System.EventHandler<System.Windows.Controls.DataGridCellEditEndingEventArgs>(this.DgvRequests_CellEditEnding);
            
            #line default
            #line hidden
            
            #line 462 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.DgvRequests.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.DgvRequests_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 24:
            this.ColCategory = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 25:
            this.ColItem = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 26:
            this.TxtDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 27:
            this.TxtRemarks = ((System.Windows.Controls.TextBox)(target));
            
            #line 622 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.TxtRemarks.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtRemarks_TextChanged);
            
            #line default
            #line hidden
            return;
            case 28:
            this.BtnAddRow = ((System.Windows.Controls.Button)(target));
            
            #line 634 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnAddRow.Click += new System.Windows.RoutedEventHandler(this.BtnAddRow_Click);
            
            #line default
            #line hidden
            return;
            case 29:
            this.BtnRemoveRow = ((System.Windows.Controls.Button)(target));
            
            #line 636 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnRemoveRow.Click += new System.Windows.RoutedEventHandler(this.BtnRemoveRow_Click);
            
            #line default
            #line hidden
            return;
            case 30:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 640 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 31:
            this.BtnSave = ((System.Windows.Controls.Button)(target));
            
            #line 642 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            this.BtnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            
            #line 83 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClearOrg_Click);
            
            #line default
            #line hidden
            break;
            case 22:
            
            #line 473 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.ChkSelectAll_Click);
            
            #line default
            #line hidden
            break;
            case 23:
            
            #line 480 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Checked += new System.Windows.RoutedEventHandler(this.RowCheck_Changed);
            
            #line default
            #line hidden
            
            #line 480 "..\..\..\..\Pages\Request\BatchAddRequestDialog.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Unchecked += new System.Windows.RoutedEventHandler(this.RowCheck_Changed);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

