#pragma checksum "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "B3EB190BF159C410806A5CAEB0426FED6E7D4C3F1B9CA30CF2A69BA714B0FAE3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Views {
    
    
    /// <summary>
    /// NonRefillableEmptyCartridgesView
    /// </summary>
    public partial class NonRefillableEmptyCartridgesView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 268 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefresh;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAssignOutbound;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCondition;
        
        #line default
        #line hidden
        
        
        #line 354 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid MainGrid;
        
        #line default
        #line hidden
        
        
        #line 481 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrev;
        
        #line default
        #line hidden
        
        
        #line 489 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNext;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/views/nonrefillableemptyc" +
                    "artridgesview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 272 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            this.BtnRefresh.Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnAssignOutbound = ((System.Windows.Controls.Button)(target));
            
            #line 278 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            this.BtnAssignOutbound.Click += new System.Windows.RoutedEventHandler(this.BtnAssignOutbound_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.CmbCondition = ((System.Windows.Controls.ComboBox)(target));
            
            #line 342 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            this.CmbCondition.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbCondition_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.MainGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 6:
            this.BtnPrev = ((System.Windows.Controls.Button)(target));
            
            #line 485 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            this.BtnPrev.Click += new System.Windows.RoutedEventHandler(this.BtnPrev_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.BtnNext = ((System.Windows.Controls.Button)(target));
            
            #line 493 "..\..\..\..\..\Wpf\CartridgeManagement\Views\NonRefillableEmptyCartridgesView.xaml"
            this.BtnNext.Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

