#pragma checksum "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0C4F976655A024E4D21FDAC1F6D8B08F1074081D3819E3970B12C772AAD147A2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// EmployeeImportSummaryWindow
    /// </summary>
    public partial class EmployeeImportSummaryWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 87 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSubtitle;
        
        #line default
        #line hidden
        
        
        #line 93 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabAdd;
        
        #line default
        #line hidden
        
        
        #line 94 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridAdd;
        
        #line default
        #line hidden
        
        
        #line 114 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabUpdate;
        
        #line default
        #line hidden
        
        
        #line 115 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridUpdate;
        
        #line default
        #line hidden
        
        
        #line 136 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem TabMissing;
        
        #line default
        #line hidden
        
        
        #line 140 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtMissingCount;
        
        #line default
        #line hidden
        
        
        #line 149 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridMissing;
        
        #line default
        #line hidden
        
        
        #line 181 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtFooterNote;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/employeeimpor" +
                    "tsummarywindow.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtSubtitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TabAdd = ((System.Windows.Controls.TabItem)(target));
            return;
            case 3:
            this.GridAdd = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 4:
            this.TabUpdate = ((System.Windows.Controls.TabItem)(target));
            return;
            case 5:
            this.GridUpdate = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 6:
            this.TabMissing = ((System.Windows.Controls.TabItem)(target));
            return;
            case 7:
            this.TxtMissingCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            
            #line 142 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSelectAllMissing_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 144 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClearAllMissing_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.GridMissing = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 11:
            this.TxtFooterNote = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            
            #line 187 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnBack_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 190 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportSummaryWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnConfirm_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

