#pragma checksum "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A06F391F6E47523F6667474A03D3130C8E2927BB16474226243B2CF5A5941D24"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.Admin.AccountManagement.Dialogs {
    
    
    /// <summary>
    /// EmployeeImportPreviewWindow
    /// </summary>
    public partial class EmployeeImportPreviewWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 139 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtFileName;
        
        #line default
        #line hidden
        
        
        #line 145 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSummary;
        
        #line default
        #line hidden
        
        
        #line 162 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearchExisting;
        
        #line default
        #line hidden
        
        
        #line 167 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridExisting;
        
        #line default
        #line hidden
        
        
        #line 212 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearchImport;
        
        #line default
        #line hidden
        
        
        #line 217 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid GridImport;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/admin/accountmanagement/dialogs/employeeimpor" +
                    "tpreviewwindow.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtFileName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtSummary = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtSearchExisting = ((System.Windows.Controls.TextBox)(target));
            
            #line 163 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            this.TxtSearchExisting.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtSearchExisting_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.GridExisting = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 5:
            
            #line 207 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSelectAllValid_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 209 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClearAll_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TxtSearchImport = ((System.Windows.Controls.TextBox)(target));
            
            #line 213 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            this.TxtSearchImport.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtSearchImport_TextChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.GridImport = ((System.Windows.Controls.DataGrid)(target));
            
            #line 226 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            this.GridImport.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.GridImport_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 259 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 262 "Wpf\Admin\AccountManagement\Dialogs\EmployeeImportPreviewWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnConfirm_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

