#pragma checksum "Pages\Software\SoftwareItemPickerDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "A02CEF539C03D27516574EA6C5CE2C1C691EB1A67A980B8E68FFFD9B0E7B5115"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Software {
    
    
    /// <summary>
    /// SoftwareItemPickerDialog
    /// </summary>
    public partial class SoftwareItemPickerDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 219 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BtnMaximizeGlyph;
        
        #line default
        #line hidden
        
        
        #line 268 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearchName;
        
        #line default
        #line hidden
        
        
        #line 273 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearchCategory;
        
        #line default
        #line hidden
        
        
        #line 278 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearchSerial;
        
        #line default
        #line hidden
        
        
        #line 295 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkShowInactive;
        
        #line default
        #line hidden
        
        
        #line 307 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ItemsGrid;
        
        #line default
        #line hidden
        
        
        #line 470 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSelectionHint;
        
        #line default
        #line hidden
        
        
        #line 481 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrevPage;
        
        #line default
        #line hidden
        
        
        #line 486 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPageInfo;
        
        #line default
        #line hidden
        
        
        #line 490 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNextPage;
        
        #line default
        #line hidden
        
        
        #line 499 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbPageSize;
        
        #line default
        #line hidden
        
        
        #line 512 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BdrSelectedCount;
        
        #line default
        #line hidden
        
        
        #line 522 "Pages\Software\SoftwareItemPickerDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSelectedCount;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/software/softwareitempickerdialog.xaml", System.UriKind.Relative);
            
            #line 1 "Pages\Software\SoftwareItemPickerDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 210 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 218 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMinimizeClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.BtnMaximizeGlyph = ((System.Windows.Controls.TextBlock)(target));
            
            #line 223 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.BtnMaximizeGlyph.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMaximizeClick);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 227 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TxtSearchName = ((System.Windows.Controls.TextBox)(target));
            
            #line 270 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.TxtSearchName.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtFilter_TextChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TxtSearchCategory = ((System.Windows.Controls.TextBox)(target));
            
            #line 275 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.TxtSearchCategory.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtFilter_TextChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TxtSearchSerial = ((System.Windows.Controls.TextBox)(target));
            
            #line 280 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.TxtSearchSerial.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtFilter_TextChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 285 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 291 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.ChkShowInactive = ((System.Windows.Controls.CheckBox)(target));
            
            #line 299 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.ChkShowInactive.Checked += new System.Windows.RoutedEventHandler(this.ChkShowInactive_Changed);
            
            #line default
            #line hidden
            
            #line 300 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.ChkShowInactive.Unchecked += new System.Windows.RoutedEventHandler(this.ChkShowInactive_Changed);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ItemsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 13:
            this.TxtSelectionHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.BtnPrevPage = ((System.Windows.Controls.Button)(target));
            
            #line 485 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.BtnPrevPage.Click += new System.Windows.RoutedEventHandler(this.BtnPrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.TxtPageInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.BtnNextPage = ((System.Windows.Controls.Button)(target));
            
            #line 494 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.BtnNextPage.Click += new System.Windows.RoutedEventHandler(this.BtnNextPage_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.CmbPageSize = ((System.Windows.Controls.ComboBox)(target));
            
            #line 503 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.CmbPageSize.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbPageSize_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.BdrSelectedCount = ((System.Windows.Controls.Border)(target));
            
            #line 521 "Pages\Software\SoftwareItemPickerDialog.xaml"
            this.BdrSelectedCount.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.BdrSelectedCount_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.TxtSelectedCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            
            #line 530 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 533 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnOk_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 12:
            
            #line 380 "Pages\Software\SoftwareItemPickerDialog.xaml"
            ((System.Windows.Controls.CheckBox)(target)).Click += new System.Windows.RoutedEventHandler(this.ChkSelectAll_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

