#pragma checksum "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "BCB9B765D64A549A74527230750826560E90F9E816E41D90E3E27C396F70C00F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Wpf.Set.BulkAddFiles {
    
    
    /// <summary>
    /// BulkAddFilesWindow
    /// </summary>
    public partial class BulkAddFilesWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 169 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddGroup;
        
        #line default
        #line hidden
        
        
        #line 174 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl GroupsPanel;
        
        #line default
        #line hidden
        
        
        #line 205 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSetSearch;
        
        #line default
        #line hidden
        
        
        #line 209 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCategoryFilter;
        
        #line default
        #line hidden
        
        
        #line 212 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup CategoryFilterPopup;
        
        #line default
        #line hidden
        
        
        #line 219 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel CategoryFilterPanel;
        
        #line default
        #line hidden
        
        
        #line 224 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid SetsGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/set/bulkaddfiles/bulkaddfileswindow.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 151 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnAddGroup = ((System.Windows.Controls.Button)(target));
            
            #line 171 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            this.BtnAddGroup.Click += new System.Windows.RoutedEventHandler(this.BtnAddGroup_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.GroupsPanel = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 4:
            this.TxtSetSearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 206 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            this.TxtSetSearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtSetSearch_TextChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BtnCategoryFilter = ((System.Windows.Controls.Button)(target));
            
            #line 211 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            this.BtnCategoryFilter.Click += new System.Windows.RoutedEventHandler(this.BtnCategoryFilter_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.CategoryFilterPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 7:
            this.CategoryFilterPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 8:
            this.SetsGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 241 "Wpf\Set\BulkAddFiles\BulkAddFilesWindow.xaml"
            this.SetsGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.SetsGrid_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

