#pragma checksum "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CDDDE9F4919ADAC1A264A17CB542C94DD296E0623F9921801874104B44D67FF3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;
using Yakult.Inventory.App.WPF.RequestPortal.AssistedRequest.ViewModels;
using Yakult.Inventory.App.WPF.Shared.Helpers;


namespace Yakult.Inventory.App.WPF.RequestPortal.AssistedRequest.Views {
    
    
    /// <summary>
    /// AssistedRequestView
    /// </summary>
    public partial class AssistedRequestView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 85 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer tourScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourAssistedBanner;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourTargetEmployeeCard;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid tourEmpFilterRow;
        
        #line default
        #line hidden
        
        
        #line 214 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox _selectEmployeeCombo;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourCartridgeSelectionCard;
        
        #line default
        #line hidden
        
        
        #line 476 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourRequestItemsCard;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourDestinationCard;
        
        #line default
        #line hidden
        
        
        #line 616 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid tourRbFilterRow;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox _receivedByCombo;
        
        #line default
        #line hidden
        
        
        #line 731 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourManualAuthCard;
        
        #line default
        #line hidden
        
        
        #line 789 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid tourDecisionRow;
        
        #line default
        #line hidden
        
        
        #line 822 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid tourAuthorizedByRow;
        
        #line default
        #line hidden
        
        
        #line 833 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox _authorizedByCombo;
        
        #line default
        #line hidden
        
        
        #line 846 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid tourAuthRemarksRow;
        
        #line default
        #line hidden
        
        
        #line 883 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border tourActionBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/requestportal/assistedrequest/views/assistedr" +
                    "equestview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tourScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 2:
            this.tourAssistedBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.tourTargetEmployeeCard = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.tourEmpFilterRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this._selectEmployeeCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 223 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
            this._selectEmployeeCombo.AddHandler(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new System.Windows.Controls.TextChangedEventHandler(this.OnSelectEmployeeTextChanged));
            
            #line default
            #line hidden
            return;
            case 6:
            this.tourCartridgeSelectionCard = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.tourRequestItemsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.tourDestinationCard = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.tourRbFilterRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this._receivedByCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 705 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
            this._receivedByCombo.AddHandler(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new System.Windows.Controls.TextChangedEventHandler(this.OnReceivedByTextChanged));
            
            #line default
            #line hidden
            return;
            case 11:
            this.tourManualAuthCard = ((System.Windows.Controls.Border)(target));
            return;
            case 12:
            this.tourDecisionRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.tourAuthorizedByRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            this._authorizedByCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 842 "..\..\..\..\..\..\Wpf\RequestPortal\AssistedRequest\Views\AssistedRequestView.xaml"
            this._authorizedByCombo.AddHandler(System.Windows.Controls.Primitives.TextBoxBase.TextChangedEvent, new System.Windows.Controls.TextChangedEventHandler(this.OnAuthorizedByTextChanged));
            
            #line default
            #line hidden
            return;
            case 15:
            this.tourAuthRemarksRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.tourActionBar = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

