#pragma checksum "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "49C71A535DE76F495CF99A8F797278A0E30ACAFC772BB072D229C035FFA6C27C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Views {
    
    
    /// <summary>
    /// ViewCartridgeSetsView
    /// </summary>
    public partial class ViewCartridgeSetsView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 285 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnOpen;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnArchive;
        
        #line default
        #line hidden
        
        
        #line 297 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnDelete;
        
        #line default
        #line hidden
        
        
        #line 303 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefresh;
        
        #line default
        #line hidden
        
        
        #line 328 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 337 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid MainGrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/views/viewcartridgesetsvi" +
                    "ew.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnOpen = ((System.Windows.Controls.Button)(target));
            
            #line 290 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            this.BtnOpen.Click += new System.Windows.RoutedEventHandler(this.BtnOpen_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnArchive = ((System.Windows.Controls.Button)(target));
            
            #line 296 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            this.BtnArchive.Click += new System.Windows.RoutedEventHandler(this.BtnArchive_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.BtnDelete = ((System.Windows.Controls.Button)(target));
            
            #line 302 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            this.BtnDelete.Click += new System.Windows.RoutedEventHandler(this.BtnDelete_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.BtnRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 307 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            this.BtnRefresh.Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.MainGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 8:
            
            #line 534 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnPrev_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 536 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnPrev_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 538 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 540 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 7:
            
            #line 512 "..\..\..\..\..\Wpf\CartridgeManagement\Views\ViewCartridgeSetsView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnRowOpen_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

