#pragma checksum "Pages\Item\CartridgeCsvImportDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "092749CA73CA77E33AF76C39965579310C357498C1D732E2EB1793968F401B88"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Item {
    
    
    /// <summary>
    /// CartridgeCsvImportDialog
    /// </summary>
    public partial class CartridgeCsvImportDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 147 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtCsvPath;
        
        #line default
        #line hidden
        
        
        #line 162 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLoadPreview;
        
        #line default
        #line hidden
        
        
        #line 169 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BannerDupes;
        
        #line default
        #line hidden
        
        
        #line 171 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblDupeNotice;
        
        #line default
        #line hidden
        
        
        #line 178 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblEmptyState;
        
        #line default
        #line hidden
        
        
        #line 184 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PreviewGrid;
        
        #line default
        #line hidden
        
        
        #line 246 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblStatus;
        
        #line default
        #line hidden
        
        
        #line 251 "Pages\Item\CartridgeCsvImportDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnImport;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/item/cartridgecsvimportdialog.xaml", System.UriKind.Relative);
            
            #line 1 "Pages\Item\CartridgeCsvImportDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 125 "Pages\Item\CartridgeCsvImportDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 129 "Pages\Item\CartridgeCsvImportDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtCsvPath = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            
            #line 161 "Pages\Item\CartridgeCsvImportDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnBrowse_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BtnLoadPreview = ((System.Windows.Controls.Button)(target));
            
            #line 164 "Pages\Item\CartridgeCsvImportDialog.xaml"
            this.BtnLoadPreview.Click += new System.Windows.RoutedEventHandler(this.BtnLoadPreview_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BannerDupes = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.LblDupeNotice = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.LblEmptyState = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.PreviewGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 10:
            this.LblStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            
            #line 250 "Pages\Item\CartridgeCsvImportDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnImport = ((System.Windows.Controls.Button)(target));
            
            #line 253 "Pages\Item\CartridgeCsvImportDialog.xaml"
            this.BtnImport.Click += new System.Windows.RoutedEventHandler(this.BtnImport_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

