#pragma checksum "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5CF62317DCCD3770B4CDDAEBE7DFB2F4AEAE3CCA142064DCDFCD3EED69AE79D4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.ConsumableManagement.Views {
    
    
    /// <summary>
    /// EditConsumableModelWindow
    /// </summary>
    public partial class EditConsumableModelWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 148 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoadingText;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel FormPanel;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtModelNumber;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCategory;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkRequestable;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkActive;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnSave;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/consumablemanagement/views/editconsumablemode" +
                    "lwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.LoadingText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.FormPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.TxtModelNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.CmbCategory = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.ChkRequestable = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.ChkActive = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.BtnSave = ((System.Windows.Controls.Button)(target));
            
            #line 204 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
            this.BtnSave.Click += new System.Windows.RoutedEventHandler(this.BtnSave_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 210 "..\..\..\..\..\Wpf\ConsumableManagement\Views\EditConsumableModelWindow.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

