#pragma checksum "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "B599316A8ADCCBAE95FF79EF26E0042E9D08B7E941F4170F4CD71B81A7A9B21D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;
using Yakult.Inventory.App.WPF.RequestPortal.RequestHistory.ViewModels;


namespace Yakult.Inventory.App.WPF.RequestPortal.RequestHistory.Views {
    
    
    /// <summary>
    /// RequestHistoryView
    /// </summary>
    public partial class RequestHistoryView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 43 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HistoryHeaderBar;
        
        #line default
        #line hidden
        
        
        #line 123 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid HistoryGrid;
        
        #line default
        #line hidden
        
        
        #line 263 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HistoryColumnHeaderZone;
        
        #line default
        #line hidden
        
        
        #line 270 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HistoryDemoRowsZone;
        
        #line default
        #line hidden
        
        
        #line 278 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border HistoryStatusZone;
        
        #line default
        #line hidden
        
        
        #line 307 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PaginationBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/requestportal/requesthistory/views/requesthis" +
                    "toryview.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HistoryHeaderBar = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.HistoryGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 143 "Wpf\RequestPortal\RequestHistory\Views\RequestHistoryView.xaml"
            this.HistoryGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.HistoryGrid_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.HistoryColumnHeaderZone = ((System.Windows.Controls.Border)(target));
            return;
            case 4:
            this.HistoryDemoRowsZone = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.HistoryStatusZone = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.PaginationBar = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

