#pragma checksum "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "51C879603783429CF525CE969C0B7E2BF49DBEA29E6F4871BBD6CC9E86BD627F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;
using Yakult.Inventory.App.WPF.Renewal.RenewalGroups.ViewModels;
using Yakult.Inventory.App.WPF.Renewal.RenewalGroups.Views;
using Yakult.Inventory.App.WPF.Shared.Controls;


namespace Yakult.Inventory.App.WPF.Renewal.RenewalGroups.Views {
    
    
    /// <summary>
    /// RenewalGroupPageView
    /// </summary>
    public partial class RenewalGroupPageView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/renewal/renewalgroups/views/renewalgrouppagev" +
                    "iew.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 222 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 223 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 224 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 225 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 226 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 227 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 228 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ColumnHeader_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 8:
            
            #line 241 "..\..\..\..\..\..\Wpf\Renewal\RenewalGroups\Views\RenewalGroupPageView.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.CardHeader_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

