#pragma checksum "Pages\Item\BatchAddItemDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "DE3193C3E10BFF10B8DE74D5374F25B840D62FC800DE6AB91E3ADA62F173CA75"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Item {
    
    
    /// <summary>
    /// BatchAddItemDialog
    /// </summary>
    public partial class BatchAddItemDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 330 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BtnMaximizeGlyph;
        
        #line default
        #line hidden
        
        
        #line 346 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblSessionCount;
        
        #line default
        #line hidden
        
        
        #line 388 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtItemName;
        
        #line default
        #line hidden
        
        
        #line 400 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtDescription;
        
        #line default
        #line hidden
        
        
        #line 411 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtModelNumber;
        
        #line default
        #line hidden
        
        
        #line 417 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowCartridgeModel;
        
        #line default
        #line hidden
        
        
        #line 429 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCartridgeModel;
        
        #line default
        #line hidden
        
        
        #line 432 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddCartridgeModel;
        
        #line default
        #line hidden
        
        
        #line 439 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowCartridgeOrigin;
        
        #line default
        #line hidden
        
        
        #line 445 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCartridgeOrigin;
        
        #line default
        #line hidden
        
        
        #line 451 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowConsumableModel;
        
        #line default
        #line hidden
        
        
        #line 463 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbConsumableModel;
        
        #line default
        #line hidden
        
        
        #line 465 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddConsumableModel;
        
        #line default
        #line hidden
        
        
        #line 492 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbItemType;
        
        #line default
        #line hidden
        
        
        #line 502 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCategory;
        
        #line default
        #line hidden
        
        
        #line 505 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddCategory;
        
        #line default
        #line hidden
        
        
        #line 512 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowServiceDateToggle;
        
        #line default
        #line hidden
        
        
        #line 519 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkServiceContractDates;
        
        #line default
        #line hidden
        
        
        #line 527 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowContractDates;
        
        #line default
        #line hidden
        
        
        #line 537 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DpStartDate;
        
        #line default
        #line hidden
        
        
        #line 542 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DpEndDate;
        
        #line default
        #line hidden
        
        
        #line 548 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowLicenseNumber;
        
        #line default
        #line hidden
        
        
        #line 555 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtLicenseNumber;
        
        #line default
        #line hidden
        
        
        #line 560 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RowWarrantyInfoBand;
        
        #line default
        #line hidden
        
        
        #line 570 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblWarrantyInfo;
        
        #line default
        #line hidden
        
        
        #line 590 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbCondition;
        
        #line default
        #line hidden
        
        
        #line 594 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbUnitOfMeasure;
        
        #line default
        #line hidden
        
        
        #line 599 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtAmount;
        
        #line default
        #line hidden
        
        
        #line 615 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowQuantity;
        
        #line default
        #line hidden
        
        
        #line 622 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtQuantity;
        
        #line default
        #line hidden
        
        
        #line 631 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowSerialNumbersEntry;
        
        #line default
        #line hidden
        
        
        #line 639 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSerialNumbers;
        
        #line default
        #line hidden
        
        
        #line 653 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel RowCellPhoneEntries;
        
        #line default
        #line hidden
        
        
        #line 656 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DgvCellPhones;
        
        #line default
        #line hidden
        
        
        #line 713 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddCellPhoneRow;
        
        #line default
        #line hidden
        
        
        #line 717 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddCellPhoneRows10;
        
        #line default
        #line hidden
        
        
        #line 721 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnDeleteCellPhoneRows;
        
        #line default
        #line hidden
        
        
        #line 729 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCellPhonePrevPage;
        
        #line default
        #line hidden
        
        
        #line 732 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCellPhonePageInfo;
        
        #line default
        #line hidden
        
        
        #line 736 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCellPhoneNextPage;
        
        #line default
        #line hidden
        
        
        #line 746 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowPreviewSection;
        
        #line default
        #line hidden
        
        
        #line 753 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPreview;
        
        #line default
        #line hidden
        
        
        #line 760 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PnlPreview;
        
        #line default
        #line hidden
        
        
        #line 770 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox LstPreview;
        
        #line default
        #line hidden
        
        
        #line 803 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbVendor;
        
        #line default
        #line hidden
        
        
        #line 805 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAddVendor;
        
        #line default
        #line hidden
        
        
        #line 812 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RowWarrantyYears;
        
        #line default
        #line hidden
        
        
        #line 819 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtWarrantyYears;
        
        #line default
        #line hidden
        
        
        #line 831 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkDatePurchased;
        
        #line default
        #line hidden
        
        
        #line 835 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DpDatePurchased;
        
        #line default
        #line hidden
        
        
        #line 848 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtPartNumber;
        
        #line default
        #line hidden
        
        
        #line 859 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkIsTrackedAsset;
        
        #line default
        #line hidden
        
        
        #line 876 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtRemarks;
        
        #line default
        #line hidden
        
        
        #line 900 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 903 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAdd;
        
        #line default
        #line hidden
        
        
        #line 906 "Pages\Item\BatchAddItemDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnDone;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/item/batchadditemdialog.xaml", System.UriKind.Relative);
            
            #line 1 "Pages\Item\BatchAddItemDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 2:
            
            #line 319 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 329 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMinimizeClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.BtnMaximizeGlyph = ((System.Windows.Controls.TextBlock)(target));
            
            #line 335 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnMaximizeGlyph.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnMaximizeClick);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 340 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.LblSessionCount = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.TxtItemName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.TxtDescription = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.TxtModelNumber = ((System.Windows.Controls.TextBox)(target));
            
            #line 413 "Pages\Item\BatchAddItemDialog.xaml"
            this.TxtModelNumber.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtModelNumber_TextChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.RowCartridgeModel = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.CmbCartridgeModel = ((System.Windows.Controls.ComboBox)(target));
            
            #line 431 "Pages\Item\BatchAddItemDialog.xaml"
            this.CmbCartridgeModel.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbCartridgeModel_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnAddCartridgeModel = ((System.Windows.Controls.Button)(target));
            
            #line 434 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddCartridgeModel.Click += new System.Windows.RoutedEventHandler(this.BtnAddCartridgeModel_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.RowCartridgeOrigin = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            this.CmbCartridgeOrigin = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.RowConsumableModel = ((System.Windows.Controls.Grid)(target));
            return;
            case 16:
            this.CmbConsumableModel = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 17:
            this.BtnAddConsumableModel = ((System.Windows.Controls.Button)(target));
            
            #line 467 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddConsumableModel.Click += new System.Windows.RoutedEventHandler(this.BtnAddConsumableModel_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.CmbItemType = ((System.Windows.Controls.ComboBox)(target));
            
            #line 494 "Pages\Item\BatchAddItemDialog.xaml"
            this.CmbItemType.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbItemType_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 19:
            this.CmbCategory = ((System.Windows.Controls.ComboBox)(target));
            
            #line 504 "Pages\Item\BatchAddItemDialog.xaml"
            this.CmbCategory.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbCategory_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.BtnAddCategory = ((System.Windows.Controls.Button)(target));
            
            #line 507 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddCategory.Click += new System.Windows.RoutedEventHandler(this.BtnAddCategory_Click);
            
            #line default
            #line hidden
            return;
            case 21:
            this.RowServiceDateToggle = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.ChkServiceContractDates = ((System.Windows.Controls.CheckBox)(target));
            
            #line 522 "Pages\Item\BatchAddItemDialog.xaml"
            this.ChkServiceContractDates.Checked += new System.Windows.RoutedEventHandler(this.ChkServiceContractDates_Changed);
            
            #line default
            #line hidden
            
            #line 523 "Pages\Item\BatchAddItemDialog.xaml"
            this.ChkServiceContractDates.Unchecked += new System.Windows.RoutedEventHandler(this.ChkServiceContractDates_Changed);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RowContractDates = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.DpStartDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 539 "Pages\Item\BatchAddItemDialog.xaml"
            this.DpStartDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.DpLicenseDate_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.DpEndDate = ((System.Windows.Controls.DatePicker)(target));
            
            #line 544 "Pages\Item\BatchAddItemDialog.xaml"
            this.DpEndDate.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.DpLicenseDate_SelectedDateChanged);
            
            #line default
            #line hidden
            return;
            case 26:
            this.RowLicenseNumber = ((System.Windows.Controls.Grid)(target));
            return;
            case 27:
            this.TxtLicenseNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            this.RowWarrantyInfoBand = ((System.Windows.Controls.Border)(target));
            return;
            case 29:
            this.LblWarrantyInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.CmbCondition = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 31:
            this.CmbUnitOfMeasure = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 32:
            this.TxtAmount = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.RowQuantity = ((System.Windows.Controls.Grid)(target));
            return;
            case 34:
            this.TxtQuantity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.RowSerialNumbersEntry = ((System.Windows.Controls.Grid)(target));
            return;
            case 36:
            this.TxtSerialNumbers = ((System.Windows.Controls.TextBox)(target));
            return;
            case 37:
            this.RowCellPhoneEntries = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 38:
            this.DgvCellPhones = ((System.Windows.Controls.DataGrid)(target));
            
            #line 673 "Pages\Item\BatchAddItemDialog.xaml"
            this.DgvCellPhones.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.DgvCellPhones_PreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 674 "Pages\Item\BatchAddItemDialog.xaml"
            this.DgvCellPhones.PreviewMouseRightButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.DgvCellPhones_PreviewMouseRightButtonDown);
            
            #line default
            #line hidden
            return;
            case 39:
            
            #line 678 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.MnuPasteCellPhoneRows_Click);
            
            #line default
            #line hidden
            return;
            case 41:
            this.BtnAddCellPhoneRow = ((System.Windows.Controls.Button)(target));
            
            #line 716 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddCellPhoneRow.Click += new System.Windows.RoutedEventHandler(this.BtnAddCellPhoneRow_Click);
            
            #line default
            #line hidden
            return;
            case 42:
            this.BtnAddCellPhoneRows10 = ((System.Windows.Controls.Button)(target));
            
            #line 720 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddCellPhoneRows10.Click += new System.Windows.RoutedEventHandler(this.BtnAddCellPhoneRows10_Click);
            
            #line default
            #line hidden
            return;
            case 43:
            this.BtnDeleteCellPhoneRows = ((System.Windows.Controls.Button)(target));
            
            #line 724 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnDeleteCellPhoneRows.Click += new System.Windows.RoutedEventHandler(this.BtnDeleteCellPhoneRows_Click);
            
            #line default
            #line hidden
            return;
            case 44:
            this.BtnCellPhonePrevPage = ((System.Windows.Controls.Button)(target));
            
            #line 731 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnCellPhonePrevPage.Click += new System.Windows.RoutedEventHandler(this.BtnCellPhonePrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            this.TxtCellPhonePageInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 46:
            this.BtnCellPhoneNextPage = ((System.Windows.Controls.Button)(target));
            
            #line 738 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnCellPhoneNextPage.Click += new System.Windows.RoutedEventHandler(this.BtnCellPhoneNextPage_Click);
            
            #line default
            #line hidden
            return;
            case 47:
            this.RowPreviewSection = ((System.Windows.Controls.Grid)(target));
            return;
            case 48:
            this.BtnPreview = ((System.Windows.Controls.Button)(target));
            
            #line 757 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnPreview.Click += new System.Windows.RoutedEventHandler(this.BtnPreview_Click);
            
            #line default
            #line hidden
            return;
            case 49:
            this.PnlPreview = ((System.Windows.Controls.Border)(target));
            return;
            case 50:
            this.LstPreview = ((System.Windows.Controls.ListBox)(target));
            return;
            case 51:
            this.CmbVendor = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 52:
            this.BtnAddVendor = ((System.Windows.Controls.Button)(target));
            
            #line 807 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAddVendor.Click += new System.Windows.RoutedEventHandler(this.BtnAddVendor_Click);
            
            #line default
            #line hidden
            return;
            case 53:
            this.RowWarrantyYears = ((System.Windows.Controls.Grid)(target));
            return;
            case 54:
            this.TxtWarrantyYears = ((System.Windows.Controls.TextBox)(target));
            return;
            case 55:
            this.ChkDatePurchased = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 56:
            this.DpDatePurchased = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 57:
            this.TxtPartNumber = ((System.Windows.Controls.TextBox)(target));
            return;
            case 58:
            this.ChkIsTrackedAsset = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 59:
            this.TxtRemarks = ((System.Windows.Controls.TextBox)(target));
            return;
            case 60:
            
            #line 898 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnImportCsv_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 902 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.BtnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 905 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnAdd.Click += new System.Windows.RoutedEventHandler(this.BtnAdd_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            this.BtnDone = ((System.Windows.Controls.Button)(target));
            
            #line 908 "Pages\Item\BatchAddItemDialog.xaml"
            this.BtnDone.Click += new System.Windows.RoutedEventHandler(this.BtnDone_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 1:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseWheelEvent;
            
            #line 86 "Pages\Item\BatchAddItemDialog.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseWheelEventHandler(this.FormCombo_PreviewMouseWheel);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            case 40:
            
            #line 706 "Pages\Item\BatchAddItemDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnRemoveCellPhoneRow_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

