-- Migration: Create Distributor table and populate from Distributors Directory.csv
-- Used by the Sales Invoice Set dialog (Distributor picker) and ViewInvoiceDetailPage.

IF NOT EXISTS (
    SELECT 1 FROM sys.objects
    WHERE object_id = OBJECT_ID(N'dbo.[Distributor]') AND type = 'U'
)
BEGIN
    CREATE TABLE dbo.[Distributor]
    (
        DistributorId INT           NOT NULL IDENTITY(1,1) PRIMARY KEY,
        Name          NVARCHAR(200) NOT NULL,
        SortOrder     INT           NULL,
        IsActive      BIT           NOT NULL DEFAULT (1),
        CreatedDate   DATETIME      NOT NULL DEFAULT (GETDATE())
    );
END

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'LACTO-B, INCORPORATED')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'LACTO-B, INCORPORATED', 1);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BIO-TECH MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BIO-TECH MARKETING CORPORATION', 2);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'MICRO-B, INCORPORATED')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'MICRO-B, INCORPORATED', 3);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BIFIDO HEALTH MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BIFIDO HEALTH MARKETING CORPORATION', 4);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'PALAWAN ULTRAHEALTH MARKETING INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'PALAWAN ULTRAHEALTH MARKETING INC.', 5);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BIOMATE CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BIOMATE CORPORATION', 6);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BACCILIFE MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BACCILIFE MARKETING CORPORATION', 7);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'NEYO CORPORATION (NUEVA ECIJA YAKULT OFFICE)')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'NEYO CORPORATION (NUEVA ECIJA YAKULT OFFICE)', 8);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'SHIROTA MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'SHIROTA MARKETING CORPORATION', 9);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'MICROFLORA HEALTH MARKETING CORP.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'MICROFLORA HEALTH MARKETING CORP.', 10);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'MICROMATE FAMILY HEALTH CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'MICROMATE FAMILY HEALTH CORPORATION', 11);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'SUPREME HEALTH MARKETING INCORPORATED')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'SUPREME HEALTH MARKETING INCORPORATED', 12);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'PROHEALTH SALES DISTRIBUTOR CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'PROHEALTH SALES DISTRIBUTOR CORPORATION', 13);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'SYNBIOTIC MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'SYNBIOTIC MARKETING CORPORATION', 14);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'ACTIGEN MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'ACTIGEN MARKETING CORPORATION', 15);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'HEALTH TUMMY CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'HEALTH TUMMY CORPORATION', 16);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BELLY FIT SALES DISTRIBUTOR INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BELLY FIT SALES DISTRIBUTOR INC.', 17);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'ISABELA GOOD HEALTH MARKETING CORP.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'ISABELA GOOD HEALTH MARKETING CORP.', 18);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'MERCHANDISE DISTRIBUTORS INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'MERCHANDISE DISTRIBUTORS INC.', 19);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'JOMAR ANNE HEALTH MARKETING INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'JOMAR ANNE HEALTH MARKETING INC.', 20);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'HENLUZ CORP./ NEGROS LONGLIFE CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'HENLUZ CORP./ NEGROS LONGLIFE CORPORATION', 21);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'PRE BIOTIC HEALTH MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'PRE BIOTIC HEALTH MARKETING CORPORATION', 22);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'GALACTO MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'GALACTO MARKETING CORPORATION', 23);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'BIO LACTIS MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'BIO LACTIS MARKETING CORPORATION', 24);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'CREST HEALTH DISTRIBUTOR')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'CREST HEALTH DISTRIBUTOR', 25);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'PROBIOTICS HEALTH MARKETING INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'PROBIOTICS HEALTH MARKETING INC.', 26);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'GENSBIO MARKETING CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'GENSBIO MARKETING CORPORATION', 27);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'LACTOBACILLUS CORPORATION')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'LACTOBACILLUS CORPORATION', 28);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'LCS CARAGA DISTRIBUTOR INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'LCS CARAGA DISTRIBUTOR INC.', 29);

IF NOT EXISTS (SELECT 1 FROM dbo.[Distributor] WHERE Name = N'LACTO FRONTIER SALES DISTRIBUTOR, INC.')
    INSERT INTO dbo.[Distributor] (Name, SortOrder) VALUES (N'LACTO FRONTIER SALES DISTRIBUTOR, INC.', 30);
