#pragma checksum "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D6F83C6BA4726471733D7FD83DFDEDB76BCC2AD65FC4CE3ECF9452D985704E4E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Yakult.Inventory.App.WPF.CartridgeManagement.Converters;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Views {
    
    
    /// <summary>
    /// DamagedEmptyCartridgesView
    /// </summary>
    public partial class DamagedEmptyCartridgesView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 258 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRefresh;
        
        #line default
        #line hidden
        
        
        #line 263 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAssignOutbound;
        
        #line default
        #line hidden
        
        
        #line 301 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 312 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid MainGrid;
        
        #line default
        #line hidden
        
        
        #line 450 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrev;
        
        #line default
        #line hidden
        
        
        #line 458 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNext;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/views/damagedemptycartrid" +
                    "gesview.xaml", System.UriKind.Relative);
            
            #line 1 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BtnRefresh = ((System.Windows.Controls.Button)(target));
            
            #line 262 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
            this.BtnRefresh.Click += new System.Windows.RoutedEventHandler(this.BtnRefresh_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.BtnAssignOutbound = ((System.Windows.Controls.Button)(target));
            
            #line 268 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
            this.BtnAssignOutbound.Click += new System.Windows.RoutedEventHandler(this.BtnAssignOutbound_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.MainGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 5:
            this.BtnPrev = ((System.Windows.Controls.Button)(target));
            
            #line 454 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
            this.BtnPrev.Click += new System.Windows.RoutedEventHandler(this.BtnPrev_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BtnNext = ((System.Windows.Controls.Button)(target));
            
            #line 462 "WPF\CartridgeManagement\Views\DamagedEmptyCartridgesView.xaml"
            this.BtnNext.Click += new System.Windows.RoutedEventHandler(this.BtnNext_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

