#pragma checksum "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9DAA8B46189366BBAE05017B6BAA927527775CCACA74CDCF2623BAD235138827"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.CartridgeManagement.Dialogs {
    
    
    /// <summary>
    /// FulfilledCartridgeDetailDialog
    /// </summary>
    public partial class FulfilledCartridgeDetailDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 82 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtTitle;
        
        #line default
        #line hidden
        
        
        #line 114 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtSetCode;
        
        #line default
        #line hidden
        
        
        #line 118 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtFulfilledAt;
        
        #line default
        #line hidden
        
        
        #line 123 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtRequester;
        
        #line default
        #line hidden
        
        
        #line 127 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtReceivedBy;
        
        #line default
        #line hidden
        
        
        #line 132 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtCompany;
        
        #line default
        #line hidden
        
        
        #line 136 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtBranch;
        
        #line default
        #line hidden
        
        
        #line 141 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtDepartment;
        
        #line default
        #line hidden
        
        
        #line 145 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtTotalIssuedQty;
        
        #line default
        #line hidden
        
        
        #line 157 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ModelsGrid;
        
        #line default
        #line hidden
        
        
        #line 218 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtEmptyState;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/cartridgemanagement/dialogs/fulfilledcartridg" +
                    "edetaildialog.xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.TxtSetCode = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TxtFulfilledAt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TxtRequester = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.TxtReceivedBy = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.TxtCompany = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.TxtBranch = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.TxtDepartment = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.TxtTotalIssuedQty = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.ModelsGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 11:
            this.TxtEmptyState = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            
            #line 233 "Wpf\CartridgeManagement\Dialogs\FulfilledCartridgeDetailDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OnClose);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

