#pragma checksum "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1A4E9B0E319A040371D88B81B06BF083A9A2FD33B95E1FBA392AD99EA994D30B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.Pages.Set {
    
    
    /// <summary>
    /// SelectRequestForSetDialog
    /// </summary>
    public partial class SelectRequestForSetDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 223 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtSearch;
        
        #line default
        #line hidden
        
        
        #line 226 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChkDateFilter;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DtpFrom;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DtpTo;
        
        #line default
        #line hidden
        
        
        #line 260 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblTitle;
        
        #line default
        #line hidden
        
        
        #line 265 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DgvRequests;
        
        #line default
        #line hidden
        
        
        #line 306 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LblPageInfo;
        
        #line default
        #line hidden
        
        
        #line 311 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnFirstPage;
        
        #line default
        #line hidden
        
        
        #line 313 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnPrevPage;
        
        #line default
        #line hidden
        
        
        #line 315 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnNextPage;
        
        #line default
        #line hidden
        
        
        #line 317 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnLastPage;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnCancel;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnAdd;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/pages/set/selectrequestforsetdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 207 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnHeaderDrag);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 211 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            ((System.Windows.Controls.TextBlock)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtSearch = ((System.Windows.Controls.TextBox)(target));
            
            #line 224 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.TxtSearch.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.TxtSearch_TextChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ChkDateFilter = ((System.Windows.Controls.CheckBox)(target));
            
            #line 228 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.ChkDateFilter.Checked += new System.Windows.RoutedEventHandler(this.DateFilter_Changed);
            
            #line default
            #line hidden
            
            #line 228 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.ChkDateFilter.Unchecked += new System.Windows.RoutedEventHandler(this.DateFilter_Changed);
            
            #line default
            #line hidden
            return;
            case 5:
            this.DtpFrom = ((System.Windows.Controls.DatePicker)(target));
            
            #line 233 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.DtpFrom.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.DateFilter_Changed);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DtpTo = ((System.Windows.Controls.DatePicker)(target));
            
            #line 243 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.DtpTo.SelectedDateChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.DateFilter_Changed);
            
            #line default
            #line hidden
            return;
            case 7:
            this.LblTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.DgvRequests = ((System.Windows.Controls.DataGrid)(target));
            
            #line 283 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.DgvRequests.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.DgvRequests_DoubleClick);
            
            #line default
            #line hidden
            
            #line 284 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.DgvRequests.Sorting += new System.Windows.Controls.DataGridSortingEventHandler(this.DgvRequests_Sorting);
            
            #line default
            #line hidden
            return;
            case 9:
            this.LblPageInfo = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.BtnFirstPage = ((System.Windows.Controls.Button)(target));
            
            #line 312 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnFirstPage.Click += new System.Windows.RoutedEventHandler(this.BtnFirstPage_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.BtnPrevPage = ((System.Windows.Controls.Button)(target));
            
            #line 314 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnPrevPage.Click += new System.Windows.RoutedEventHandler(this.BtnPrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.BtnNextPage = ((System.Windows.Controls.Button)(target));
            
            #line 316 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnNextPage.Click += new System.Windows.RoutedEventHandler(this.BtnNextPage_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.BtnLastPage = ((System.Windows.Controls.Button)(target));
            
            #line 318 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnLastPage.Click += new System.Windows.RoutedEventHandler(this.BtnLastPage_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.BtnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 328 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnCancel.Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.BtnAdd = ((System.Windows.Controls.Button)(target));
            
            #line 330 "..\..\..\..\Pages\Set\SelectRequestForSetDialog.xaml"
            this.BtnAdd.Click += new System.Windows.RoutedEventHandler(this.BtnAdd_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

