using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using Yakult.Inventory.App.Models;

namespace Yakult.Inventory.App.Helpers
{
    /// <summary>
    /// Generates an audit-ready PDF report from User Activity data using PDFsharp.
    /// Output: Landscape A4, professional layout suitable for management review.
    /// </summary>
    public static class UserActivityPdfGenerator
    {
        private const string CompanyName = "Yakult Philippines Inc.";
        private const string SystemName = "Yakult Inventory Monitoring System";
        private const string ReportTitle = "User Activity Report";
        private const string FooterText = "Generated by Inventory Monitoring System";

        // Brand color — teal, consistent with the application theme
        private static readonly XColor TealColor = XColor.FromArgb(0, 150, 136);
        private static readonly XColor TealLight = XColor.FromArgb(224, 247, 245);
        private static readonly XColor HeaderRowColor = XColor.FromArgb(38, 166, 154);
        private static readonly XColor AltRowColor = XColor.FromArgb(245, 245, 245);
        private static readonly XColor ApproveRowColor = XColor.FromArgb(232, 245, 233);
        private static readonly XColor RejectRowColor = XColor.FromArgb(255, 235, 238);

        public static void Generate(
            IReadOnlyList<UserActivityLogDto> activities,
            UserActivityFilter filter,
            string outputPath,
            IReadOnlyCollection<string> visibleColumns = null)
        {
            if (activities == null) throw new ArgumentNullException(nameof(activities));
            if (string.IsNullOrWhiteSpace(outputPath)) throw new ArgumentNullException(nameof(outputPath));

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            var doc = new PdfDocument
            {
                Info =
                {
                    Title = ReportTitle,
                    Subject = "User Activity Audit Report",
                    Author = SystemName,
                    Creator = SystemName
                }
            };

            var fontTitle = new XFont("Segoe UI", 18, XFontStyle.Bold);
            var fontCompany = new XFont("Segoe UI", 10, XFontStyle.Regular);
            var fontMeta = new XFont("Segoe UI", 9, XFontStyle.Regular);
            var fontMetaBold = new XFont("Segoe UI", 9, XFontStyle.Bold);
            var fontTableHeader = new XFont("Segoe UI", 8, XFontStyle.Bold);
            var fontTableCell = new XFont("Segoe UI", 7.5, XFontStyle.Regular);
            var fontFooter = new XFont("Segoe UI", 8, XFontStyle.Italic);
            var fontFilterLabel = new XFont("Segoe UI", 8.5, XFontStyle.Bold);
            var fontFilterValue = new XFont("Segoe UI", 8.5, XFontStyle.Regular);

            // All column definitions: param name, header, default width (0 = fill remainder)
            string[] allParams  = { "ShowDateTime", "ShowUser", "ShowEmail", "ShowAction", "ShowEntityType", "ShowEntityId", "ShowDescription" };
            string[] allHeaders = { "Date & Time",  "User",     "Email",     "Action",     "Entity Type",    "Entity ID",    "Description" };
            double[] allWidths  = {  95.0,           90.0,       105.0,       68.0,         72.0,             48.0,           0.0 };

            int[] colIdx = Enumerable.Range(0, allParams.Length)
                .Where(i => visibleColumns == null || visibleColumns.Contains(allParams[i]))
                .ToArray();
            if (colIdx.Length == 0) colIdx = new[] { 0 };

            // Table column definitions: (Header, Width) — filtered to visible columns
            var columns = colIdx.Select(i => (allHeaders[i], allWidths[i])).ToArray();

            const double margin = 22;
            const double rowHeight = 16;
            const double headerRowHeight = 18;

            var safeActivities = activities.Where(a => a != null).ToList();
            int totalRows = safeActivities.Count;
            int pageNumber = 0;
            PdfPage page = null;
            XGraphics gfx = null;
            double y = 0;
            double tableTop = 0;
            double tableWidth = 0;
            double[] colWidths = null;

            void BeginPage()
            {
                pageNumber++;
                page = doc.AddPage();
                page.Orientation = PdfSharp.PageOrientation.Landscape;
                page.Size = PdfSharp.PageSize.A4;
                gfx = XGraphics.FromPdfPage(page);

                tableWidth = page.Width - margin * 2;

                // Distribute remainder to the last column only if its nominal width is 0
                bool hasFill = columns.Length > 0 && columns[columns.Length - 1].Item2 == 0.0;
                double fixedTotal = columns.Take(hasFill ? columns.Length - 1 : columns.Length).Sum(c => c.Item2);
                double remainderWidth = Math.Max(60, tableWidth - fixedTotal);
                colWidths = columns.Select((c, i) =>
                    (hasFill && i == columns.Length - 1) ? remainderWidth : c.Item2).ToArray();

                y = margin;

                // ── Page header band ──────────────────────────────────────────
                double headerBandH = pageNumber == 1 ? 110 : 28;
                gfx.DrawRectangle(new XSolidBrush(TealColor),
                    new XRect(0, 0, page.Width, headerBandH));

                if (pageNumber == 1)
                {
                    // System name
                    gfx.DrawString(CompanyName, fontCompany,
                        XBrushes.White,
                        new XRect(margin, 12, page.Width - margin * 2, 14),
                        XStringFormats.TopLeft);

                    // Report title
                    gfx.DrawString(ReportTitle, fontTitle,
                        XBrushes.White,
                        new XRect(margin, 28, page.Width - margin * 2, 26),
                        XStringFormats.TopLeft);

                    // Generated date
                    string genDate = $"Generated: {DateTime.Now:dddd, dd MMMM yyyy  HH:mm:ss}";
                    gfx.DrawString(genDate, fontMeta,
                        XBrushes.White,
                        new XRect(margin, 58, page.Width - margin * 2, 14),
                        XStringFormats.TopLeft);

                    // Filter summary
                    string filterSummary = BuildFilterSummary(filter);
                    gfx.DrawString("Applied Filters:  ", fontMetaBold,
                        XBrushes.White,
                        new XRect(margin, 74, 120, 14),
                        XStringFormats.TopLeft);
                    gfx.DrawString(filterSummary, fontMeta,
                        XBrushes.White,
                        new XRect(margin + 90, 74, page.Width - margin * 2 - 90, 14),
                        XStringFormats.TopLeft);

                    // Record count
                    string countStr = $"Total records: {totalRows:N0}";
                    gfx.DrawString(countStr, fontMeta,
                        XBrushes.White,
                        new XRect(margin, 90, page.Width - margin * 2, 14),
                        XStringFormats.TopLeft);

                    y = headerBandH + 10;
                }
                else
                {
                    // Continuation pages: compact header
                    gfx.DrawString($"{ReportTitle}  (cont.)", fontMetaBold,
                        XBrushes.White,
                        new XRect(margin, 8, page.Width - 200, 14),
                        XStringFormats.TopLeft);
                    string pageStr = $"Page {pageNumber}";
                    gfx.DrawString(pageStr, fontMeta,
                        XBrushes.White,
                        new XRect(0, 8, page.Width - margin, 14),
                        XStringFormats.TopRight);

                    y = headerBandH + 8;
                }

                tableTop = y;

                // ── Column header row ─────────────────────────────────────────
                gfx.DrawRectangle(new XSolidBrush(HeaderRowColor),
                    new XRect(margin, y, tableWidth, headerRowHeight));

                double x = margin;
                for (int ci = 0; ci < columns.Length; ci++)
                {
                    gfx.DrawString(columns[ci].Item1, fontTableHeader,
                        XBrushes.White,
                        new XRect(x + 3, y + 4, colWidths[ci] - 6, headerRowHeight - 4),
                        XStringFormats.TopLeft);
                    x += colWidths[ci];
                }
                y += headerRowHeight;
            }

            void DrawFooter()
            {
                if (gfx == null) return;
                double footerY = page.Height - 18;
                gfx.DrawLine(new XPen(XColor.FromArgb(200, 200, 200), 0.5),
                    margin, footerY - 4, page.Width - margin, footerY - 4);
                gfx.DrawString(FooterText, fontFooter,
                    new XSolidBrush(XColor.FromArgb(130, 130, 130)),
                    new XRect(margin, footerY, page.Width - margin * 2, 12),
                    XStringFormats.TopLeft);
                string pgStr = $"Page {pageNumber}";
                gfx.DrawString(pgStr, fontFooter,
                    new XSolidBrush(XColor.FromArgb(130, 130, 130)),
                    new XRect(0, footerY, page.Width - margin, 12),
                    XStringFormats.TopRight);
            }

            BeginPage();
            double pageBottom = page.Height - 28; // leave room for footer

            for (int ri = 0; ri < safeActivities.Count; ri++)
            {
                if (y + rowHeight > pageBottom)
                {
                    DrawFooter();
                    BeginPage();
                    pageBottom = page.Height - 28;
                }

                var item = safeActivities[ri];
                bool isApprove = string.Equals(item.ActionType, "Approve", StringComparison.OrdinalIgnoreCase);
                bool isReject = string.Equals(item.ActionType, "Reject", StringComparison.OrdinalIgnoreCase);
                bool isAlt = ri % 2 == 1;

                XBrush rowBg = isApprove ? new XSolidBrush(ApproveRowColor)
                    : isReject ? new XSolidBrush(RejectRowColor)
                    : isAlt ? new XSolidBrush(AltRowColor)
                    : XBrushes.White;

                gfx.DrawRectangle(rowBg, new XRect(margin, y, tableWidth, rowHeight));

                // Subtle left accent for approve/reject
                if (isApprove)
                    gfx.DrawRectangle(new XSolidBrush(XColor.FromArgb(76, 175, 80)),
                        new XRect(margin, y, 3, rowHeight));
                else if (isReject)
                    gfx.DrawRectangle(new XSolidBrush(XColor.FromArgb(229, 57, 53)),
                        new XRect(margin, y, 3, rowHeight));

                // Grid line at bottom of row
                gfx.DrawLine(new XPen(XColor.FromArgb(220, 220, 220), 0.3),
                    margin, y + rowHeight, margin + tableWidth, y + rowHeight);

                // Cell content — only visible columns in colIdx order
                string[] allRowValues = new[]
                {
                    item.CreatedDate.ToString("yyyy-MM-dd HH:mm:ss"),
                    item.Name ?? "",
                    item.EmailAddress ?? "",
                    item.ActionType ?? "",
                    item.EntityType ?? "",
                    item.EntityId?.ToString() ?? "",
                    item.Description ?? ""
                };
                var cellValues = colIdx.Select(i => allRowValues[i]).ToArray();

                XBrush textBrush = isApprove || isReject
                    ? XBrushes.Black
                    : new XSolidBrush(XColor.FromArgb(40, 40, 40));

                double cx = margin;
                for (int ci = 0; ci < cellValues.Length; ci++)
                {
                    string text = TruncatePdf(cellValues[ci], colWidths[ci], fontTableCell, gfx);
                    gfx.DrawString(text, fontTableCell, textBrush,
                        new XRect(cx + 4, y + 3, colWidths[ci] - 6, rowHeight - 3),
                        XStringFormats.TopLeft);
                    cx += colWidths[ci];
                }

                y += rowHeight;
            }

            // Draw empty state if no records
            if (safeActivities.Count == 0)
            {
                gfx.DrawString("No activity records match the applied filters.",
                    fontMeta, new XSolidBrush(XColor.FromArgb(130, 130, 130)),
                    new XRect(margin, y + 10, tableWidth, 20),
                    XStringFormats.TopLeft);
            }

            DrawFooter();

            doc.Save(outputPath);
        }

        // ─────────────────────────────────────────────────────────────
        //  Helpers
        // ─────────────────────────────────────────────────────────────

        private static string BuildFilterSummary(UserActivityFilter filter)
        {
            var parts = new List<string>();
            if (filter.DateFrom.HasValue) parts.Add($"From {filter.DateFrom.Value:dd MMM yyyy}");
            if (filter.DateTo.HasValue) parts.Add($"To {filter.DateTo.Value:dd MMM yyyy}");
            if (!string.IsNullOrWhiteSpace(filter.ActionType)) parts.Add($"Action: {filter.ActionType}");
            if (!string.IsNullOrWhiteSpace(filter.EntityType)) parts.Add($"Entity: {filter.EntityType}");
            return parts.Count > 0 ? string.Join("   |   ", parts) : "None (all records shown)";
        }

        /// <summary>
        /// Truncates a string so it fits within the given pixel width using the specified font.
        /// Appends "…" if truncated.
        /// </summary>
        private static string TruncatePdf(string text, double maxWidth, XFont font, XGraphics gfx)
        {
            if (string.IsNullOrEmpty(text)) return text;
            double usable = maxWidth - 8;
            if (gfx.MeasureString(text, font).Width <= usable) return text;

            while (text.Length > 1)
            {
                text = text.Substring(0, text.Length - 1);
                if (gfx.MeasureString(text + "…", font).Width <= usable)
                    return text + "…";
            }
            return "…";
        }
    }
}
