#pragma checksum "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1688C0FADBD65C4D4F022D677054F5BF370B5366C45FC545CCC0BA4BF5B1799E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Yakult.Inventory.App.WPF.RequestPortal.WalkThrough {
    
    
    /// <summary>
    /// WpfPortalTourWindow
    /// </summary>
    public partial class WpfPortalTourWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas RootCanvas;
        
        #line default
        #line hidden
        
        
        #line 16 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path OverlayPath;
        
        #line default
        #line hidden
        
        
        #line 22 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle HighlightRing;
        
        #line default
        #line hidden
        
        
        #line 31 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PopoverBorder;
        
        #line default
        #line hidden
        
        
        #line 55 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TitleText;
        
        #line default
        #line hidden
        
        
        #line 69 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StepCounterText;
        
        #line default
        #line hidden
        
        
        #line 83 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DescriptionText;
        
        #line default
        #line hidden
        
        
        #line 92 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl BulletList;
        
        #line default
        #line hidden
        
        
        #line 120 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DemoBanner;
        
        #line default
        #line hidden
        
        
        #line 153 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PrevButton;
        
        #line default
        #line hidden
        
        
        #line 189 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SkipButton;
        
        #line default
        #line hidden
        
        
        #line 223 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NextButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Yakult.Inventory.App;component/wpf/requestportal/walkthrough/wpfportaltourwindow" +
                    ".xaml", System.UriKind.Relative);
            
            #line 1 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 11 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            ((Yakult.Inventory.App.WPF.RequestPortal.WalkThrough.WpfPortalTourWindow)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.Window_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.RootCanvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 3:
            this.OverlayPath = ((System.Windows.Shapes.Path)(target));
            
            #line 19 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            this.OverlayPath.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.Overlay_MouseDown);
            
            #line default
            #line hidden
            return;
            case 4:
            this.HighlightRing = ((System.Windows.Shapes.Rectangle)(target));
            return;
            case 5:
            this.PopoverBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.TitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.StepCounterText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.DescriptionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.BulletList = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 10:
            this.DemoBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.PrevButton = ((System.Windows.Controls.Button)(target));
            
            #line 156 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            this.PrevButton.Click += new System.Windows.RoutedEventHandler(this.PrevButton_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.SkipButton = ((System.Windows.Controls.Button)(target));
            
            #line 192 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            this.SkipButton.Click += new System.Windows.RoutedEventHandler(this.SkipButton_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.NextButton = ((System.Windows.Controls.Button)(target));
            
            #line 226 "Wpf\RequestPortal\WalkThrough\WpfPortalTourWindow.xaml"
            this.NextButton.Click += new System.Windows.RoutedEventHandler(this.NextButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

