namespace Inventory.RequestPortal.Models.ViewModels
{
    /// <summary>
    /// Snapshot of a request submission showing EXACTLY what the user entered.
    /// Used for Google Forms / Microsoft Forms-style confirmation view.
    ///
    /// IMPORTANT: This is NOT queried from the database.
    /// Values are captured directly from the submitted form to avoid unreliable historical data.
    /// </summary>
    public class RequestSubmissionSnapshotViewModel
    {
        /// <summary>
        /// The cartridge model number entered/selected by the user.
        /// </summary>
        public string CartridgeModel { get; set; } = string.Empty;

        /// <summary>
        /// Quantity requested by the user.
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Good empty cartridges returned (replaces CartridgeCondition).
        /// </summary>
        public int GoodEmptyQty { get; set; }

        /// <summary>
        /// Damaged empty cartridges returned (replaces CartridgeCondition).
        /// </summary>
        public int DamagedEmptyQty { get; set; }

        public List<RequestSubmissionItemSnapshotViewModel> Items { get; set; } = new List<RequestSubmissionItemSnapshotViewModel>();

        /// <summary>
        /// Requester name (employee name).
        /// </summary>
        public string RequesterName { get; set; } = string.Empty;

        /// <summary>
        /// Requester position (employee position).
        /// </summary>
        public string RequesterPosition { get; set; } = string.Empty;

        /// <summary>
        /// Company name.
        /// </summary>
        public string Company { get; set; } = string.Empty;

        /// <summary>
        /// Branch name.
        /// </summary>
        public string Branch { get; set; } = string.Empty;

        /// <summary>
        /// Department name.
        /// </summary>
        public string Department { get; set; } = string.Empty;

        /// <summary>
        /// Distribution method: "PICKUP" or "DELIVERY"
        /// </summary>
        public string DistributionMethod { get; set; } = string.Empty;

        /// <summary>
        /// Name of the designated receiver (only applicable for PICKUP).
        /// </summary>
        public string? ReceivedByName { get; set; }

        /// <summary>
        /// Additional remarks entered by the user.
        /// </summary>
        public string? AdditionalRemarks { get; set; }

        /// <summary>
        /// When the submission was made.
        /// </summary>
        public DateTime SubmissionDate { get; set; }

        /// <summary>
        /// Status is always "Submitted" for snapshots.
        /// </summary>
        public string Status => "Submitted";

        /// <summary>
        /// Request IDs generated by the system (for reference).
        /// </summary>
        public List<int> RequestIds { get; set; } = new List<int>();
    }

    public class RequestSubmissionItemSnapshotViewModel
    {
        public string CartridgeModel { get; set; } = string.Empty;
        public int Quantity { get; set; }
        public int GoodEmptyQty { get; set; }
        public int DamagedEmptyQty { get; set; }
    }
}
